### Minicurso de Pandas

Carregamento dos Dados

In [1]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

url = "https://raw.githubusercontent.com/tmoura/machinelearning/master/iris.data"

#url = "/content/sample_data/transfusion.data"

df = pd.read_csv(url, header=None) # Carregar dataset

columns = len(df.columns)

y = df[0] # extrai a primeira coluna, que é o label
X = df.loc[:,1:columns-1]

Criando um DataFrame

In [2]:
data = {
'País': ['Bélgica', 'Índia', 'Brasil'],
'Capital': ['Bruxelas', 'Nova Delhi', 'Brasília'],
'População': [123465, 456789, 987654]
}

df = pd.DataFrame(data, columns=['País','Capital','População'])

df

      País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

Copiar DataFrame

In [3]:
df2 = df.copy()

df2['Capital'] = 'teste'

display(df2)

display(df)

      País Capital  População
0  Bélgica   teste     123465
1    Índia   teste     456789
2   Brasil   teste     987654

      País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

Informações sobre o dataset

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   País       3 non-null      object
 1   Capital    3 non-null      object
 2   População  3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

Descrição do dataset

In [5]:
#df = df.drop('População',axis=1)
df.describe()

           População
count       3.000000
mean   522636.000000
std    435841.172317
min    123465.000000
25%    290127.000000
50%    456789.000000
75%    722221.500000
max    987654.000000

Dimensão do dataset

In [6]:
df.shape

(3, 3)

Pegar apenas algumas linhas do DF

In [7]:
df.head(2) # mostra apenas as 2 primeiras linhas
#df.head()  # mostra apenas as 5 primeiras linhas

      País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789

Ordenando os dados do DF

In [8]:
df = df.sort_values('Capital')
#df.sort_values('Capital',inplace=True)

display(df)

#Ordenando em ordem decrescente
df = df.sort_values('Capital',ascending=False)

display(df)

      País     Capital  População
2   Brasil    Brasília     987654
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789

      País     Capital  População
1    Índia  Nova Delhi     456789
0  Bélgica    Bruxelas     123465
2   Brasil    Brasília     987654

Descrição dos ÍNDICES e COLUNAS

In [9]:
display(df.index)

display(df.columns)

Index([1, 0, 2], dtype='int64')

Index(['País', 'Capital', 'População'], dtype='object')

Uso do "loc" e "iloc"

loc é usado para selecionarmos linhas e colunas usando o label

iloc é usado para cessar as linhas e colunas pelo índice

In [10]:

print(df.columns.values, '\n')

print(df.loc[:,'Capital'], '\n') # qualquer linha, coluna Capital
print(df.loc[1,'Capital'], '\n') # linha 1, coluna 'Capital'

print(df.iloc[:,1], '\n') # qualquer linha, coluna 1
print(df.iloc[1,1], '\n') # linha 1, coluna 1

['País' 'Capital' 'População']

1    Nova Delhi
0      Bruxelas
2      Brasília
Name: Capital, dtype: object

Nova Delhi

1    Nova Delhi
0      Bruxelas
2      Brasília
Name: Capital, dtype: object

Bruxelas

Removendo linhas/colunas

In [11]:
#df.drop('Capital') #ERRO
df.drop('Capital',axis=1) # Apaga a coluna 'Capital' inteira

df.drop(1) # Apaga a linha 1 inteira

#display(df)

      País   Capital  População
0  Bélgica  Bruxelas     123465
2   Brasil  Brasília     987654

Nova Coluna em um DataFrame

In [12]:
df['Nova Coluna'] = 0

df

      País     Capital  População  Nova Coluna
1    Índia  Nova Delhi     456789            0
0  Bélgica    Bruxelas     123465            0
2   Brasil    Brasília     987654            0

Nova Linha em um DataFrame

In [13]:
cols =  ['País', 'Capital', 'População']

new_line = ['Argentina','Buenos Aires',153700]
new_line = pd.DataFrame([new_line], columns=cols)

df = pd.concat([df,new_line],ignore_index = True)

df

        País       Capital  População  Nova Coluna
0      Índia    Nova Delhi     456789          0.0
1    Bélgica      Bruxelas     123465          0.0
2     Brasil      Brasília     987654          0.0
3  Argentina  Buenos Aires     153700          NaN

Resumo dos Dados

In [15]:
print(df.sum(),'\n')

#Menor valor de um DataFrame
print(df.min(),'\n')

#Maior valor
print(df.max(),'\n')

#Média dos valores
print(df.mean(numeric_only=True),'\n')

#Mediana dos valores
print(df.median(numeric_only=True),'\n')

País                      ÍndiaBélgicaBrasilArgentina
Capital        Nova DelhiBruxelasBrasíliaBuenos Aires
População                                     1721608
Nova Coluna                                       0.0
dtype: object

País           Argentina
Capital         Brasília
População         123465
Nova Coluna          0.0
dtype: object

País                Índia
Capital        Nova Delhi
População          987654
Nova Coluna           0.0
dtype: object

População      430402.0
Nova Coluna         0.0
dtype: float64

População      305244.5
Nova Coluna         0.0
dtype: float64

Filtragem do DataFrame

In [16]:
df[df['População'] % 2 == 0]

        País       Capital  População  Nova Coluna
2     Brasil      Brasília     987654          0.0
3  Argentina  Buenos Aires     153700          NaN

### Funções Importantes - Scikit Learning

Normalização de uma Coluna

In [17]:
import pandas as pd

data = {
'País': ['Bélgica', 'Índia', 'Brasil'],
'Capital': ['Bruxelas', 'Nova Delhi', 'Brasília'],
'População': [123465, 456789, 987654]
}

df = pd.DataFrame(data, columns=['País','Capital','População'])

# Normalização: Deixar os valores entre 0 e 1

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# O uso de -1 indica que vc não sabe o tamanho da dimensão. A matrix vai se ajustar automaticamente
df['População'] = MinMaxScaler().fit_transform(np.array(df['População']).reshape(-1,1))

df

      País     Capital  População
0  Bélgica    Bruxelas   0.000000
1    Índia  Nova Delhi   0.385707
2   Brasil    Brasília   1.000000

De categórico para numérico

In [18]:
from sklearn.preprocessing import LabelBinarizer

teste = LabelBinarizer().fit_transform(df['Capital'])

new_df = pd.DataFrame(teste)

df_final = pd.concat([df,new_df],axis=1) # concatena na coluna com axis=1, default axis=0

df_final = df_final.drop('Capital',axis=1)

df_final

      País  População  0  1  2
0  Bélgica   0.000000  0  1  0
1    Índia   0.385707  0  0  1
2   Brasil   1.000000  1  0  0

Transformar de DataFrame ou Series para LIST PYTHON

In [19]:
df.values.tolist()

[['Bélgica', 'Bruxelas', 0.0],
 ['Índia', 'Nova Delhi', 0.38570729319628],
 ['Brasil', 'Brasília', 1.0]]

### NumPy

ARRAY: Transformar um DataFrame ou Serie em Array

In [20]:
import numpy as np

pop = df['População']

pop_array = np.array(pop)

pop_array[0]

np.float64(0.0)

ARRAY de Zeros

In [21]:
import numpy as np

matrix_zeros = np.zeros((4,3))

matrix_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

ARRAY de 1

In [22]:
import numpy as np

matrix_ones = np.ones((4,3))

matrix_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Ordenação

In [23]:
import numpy as np

arr = np.array([3,1,0,9,4,7])

np.sort(arr)

array([0, 1, 3, 4, 7, 9])